services:
  graph:
    profiles:
      - "test"
    extends:
      file: recipes/docker-compose.yml
      service: graph
    volumes:
      - "graphdb_home:/opt/graphdb/home"
      - "./recipes/scripts:/usr/src/neurobagel/scripts"
      - "./recipes/vocab:/usr/src/neurobagel/vocab"
      - "./neurobagel_examples/data-upload/pheno-bids-derivatives-output:/data"
    environment:
      NB_GRAPH_USERNAME: "DBUSER"
      NB_GRAPH_DB: "repositories/my_db"
    secrets:
      - db_admin_password
      - db_user_password

  api:
    profiles:
      - "test"
    extends:
      file: recipes/docker-compose.yml
      service: api
    container_name: "node-api"
    environment:
      NB_GRAPH_USERNAME: "DBUSER"
      NB_RETURN_AGG: false
    volumes:
      - './recipes/scripts/api_entrypoint.sh:/usr/src/api_entrypoint.sh'
    build:
      context: apps/node-api
      dockerfile: Dockerfile
    secrets:
      - db_user_password
    
  federation:
    profiles:
      - "test"
    extends:
      file: recipes/docker-compose.yml
      service: federation
    container_name: "federation-api"
    build:
      context: apps/federation-api
      dockerfile: Dockerfile
    volumes:
      - './dev/local_nb_nodes.json:/usr/src/local_nb_nodes.json:ro'
  
secrets:
  db_admin_password:
    file: ./recipes/secrets/NB_GRAPH_ADMIN_PASSWORD.txt
  db_user_password:
    file: ./recipes/secrets/NB_GRAPH_PASSWORD.txt

volumes:
  graphdb_home: