name: Build Docker nightly image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        app: [{image_name: api, path: ./apps/node-api}, {image_name: federation_api, path: ./apps/federation-api}]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.app.path }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.app.image_name }}:nightly
